name: resubscribe_flutter_sdk
version: 1.0.8
description: The Flutter sdk for Resubscribe
homepage: https://github.com/resubscribe/resubscribe-flutter-sdk

# Limited to ios and android because webview_flutter is not supported on web
platforms:
  ios:
  android:

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
