name: resubscribe_flutter_sdk
version: 1.0.0
description: The Flutter sdk for Resubscribe
homepage: https://github.com/resubscribe/resubscribe-flutter-sdk

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
