name: resubscribe_flutter_sdk
version: 1.0.11
description: The Flutter sdk for Resubscribe
homepage: https://github.com/resubscribe/resubscribe-flutter-sdk

# Limited to ios and android because webview_flutter is not supported on web
platforms:
  ios:
  android:

topics:
  - user-interviews
  - user-research
  - feedback

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  webview_flutter: ^4.7.0
